replicaCount: 2

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30081

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

