apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: nginx-lab
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
    - port: 3306         # Port interne au cluster
      targetPort: 3306   # Port dans le conteneur
      nodePort: 30306    # Port exposé sur le node

