name: Auto Deploy Helm Chart to k8s-master

on:
  push:
    branches:
      - main
    paths:
      - 'nginx-custom-chart/**'
      - '.github/workflows/helm-auto-deploy.yml'

jobs:
  deploy:
    name: Deploy via self-hosted runner
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Déploiement Helm local
        run: |
          cd nginx-custom-chart
          helm upgrade --install mon-nginx ./ --namespace nginx-lab --create-namespace

