name: Auto Deploy Helm Chart to k8s-master

on:
  push:
    branches:
      - main
    paths:
      - 'nginx-custom-chart/**'
      - '.github/workflows/helm-auto-deploy.yml'

jobs:
  deploy:
    name: Deploy via SSH to k8s-master
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_ed25519
          chmod 600 $HOME/.ssh/id_ed25519
          ssh-keyscan -H 10.0.0.2 >> $HOME/.ssh/known_hosts



      - name: Run Helm on remote host
        run: |
          ssh -i ~/.ssh/id_ed25519 costac@10.0.0.2 << 'EOF'
            cd ~/nginx-custom-chart
            helm upgrade --install mon-nginx ./ --namespace nginx-lab --create-namespace
          EOF

