name: Auto Deploy Helm Chart to k8s-master

on:
  push:
    branches:
      - main
    paths:
      - 'nginx-custom-chart/**'
      - '.github/workflows/helm-auto-deploy.yml'

jobs:
  deploy:
    name: Deploy via SSH to k8s-master
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write SSH key to file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add known hosts
        run: |
          ssh-keyscan 10.0.0.2 >> ~/.ssh/known_hosts

      - name: Run Helm on remote host
        run: |
          ssh -i ~/.ssh/id_ed25519 costac@10.0.0.2 << 'EOF'
            cd ~/nginx-custom-chart
            helm upgrade --install mon-nginx ./ --namespace nginx-lab --create-namespace
          EOF

