name: Kubernetes YAML Linter

on:
  push:
    paths:
      - '**.yaml'
      - '**.yml'
      - '.github/workflows/**'

jobs:
  kube-lint:
    runs-on: ubuntu-latest
    name: Lint YAML Kubernetes files

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kubeval
        run: |
          curl -LO https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar -xzf kubeval-linux-amd64.tar.gz
          chmod +x kubeval
          sudo mv kubeval /usr/local/bin/kubeval
      - name: Run kubeval on YAML files
        run: |
          find . -name "*.yaml" ! -name "nginx-ingress.yaml" -print0 | xargs -0 -r -I {} kubeval {}

