name: Lint Kubernetes YAML

on:
  push:
    branches:
      - main
    paths:
      - '**/*.yaml'

jobs:
  lint:
    name: Validate YAML with kubeval
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubeval
        run: |
          wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          sudo mv kubeval /usr/local/bin

      - name: Lint YAML (sans Helm)
        run: |
          find . -name '*.yaml' \
            ! -path "./nginx-custom-chart/*" \
            -exec kubeval {} +

